apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.operator.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Values.operator.name }}
  template:
    metadata:
      labels:
        name: {{ .Values.operator.name }}
    spec:
      serviceAccountName: {{ .Values.operator.name }}
      containers:
        - name: {{ .Values.operator.name }}
          # Replace this with the built image name
          image: {{ .Values.operator.image }}
          command:
          - {{ .Values.operator.name }}
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "{{ .Values.operator.name }}"
          livenessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - stat
                - /tmp/operator-sdk-ready
            initialDelaySeconds: 5
            periodSeconds: 10
