---
language: go
go:
  - 1.14.x
services:
  - docker
install:
  - make travis
script:
  - set -e
  - make
  - make test-e2e TEST_IMAGE_REPO="$(./hack/install-registry.sh show):5000/shipwright-io/build-e2e"
  - set +e
deploy:
  - provider: script
    script: make release TAG=latest
    on:
      branch: master
  - provider: script
    script: make release TAG=$TRAVIS_TAG
    on:
      tags: true
      all_branches: true
