apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: bc-run
spec:
  serviceAccountName: pipeline
  taskRef:
    name: buildpacks-v3
  podTemplate:
    volumes:
    - name: my-cache
      persistentVolumeClaim:
        claimName: my-volume-claim
  inputs:
    resources:
    - name: source
      resourceSpec:
        type: git
        params:
        - name: url
          value: https://github.com/sclorg/nodejs-ex
    params:
    - name: BUILDER_IMAGE
      value: cloudfoundry/cnb:bionic
    - name: CACHE
      value: my-cache
  outputs:
    resources:
    - name: image
      resourceSpec:
        type: image
        params:
        - name: url
          value: image-registry.openshift-image-registry.svc:5000/sbose/nodejs-ex-buildpacks