apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: builds.build.dev
spec:
  group: build.dev
  names:
    kind: Build
    listKind: BuildList
    plural: builds
    singular: build
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Build is the Schema for the builds API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: BuildSpec defines the desired state of Build
          properties:
            builderImage:
              type: string
            dockerfile:
              type: string
            outputImage:
              type: string
            parameters:
              description: Parameter defines the data structure that would be used
                for expressing arbitrary key/value pairs for the execution of a build
              properties:
                name:
                  type: string
                value:
                  type: string
              required:
              - name
              - value
              type: object
            pathContext:
              type: string
            source:
              description: GitSource contains the versioned source code metadata This
                is similar to OpenShift BuildConfig Git Source API
              properties:
                contextDir:
                  description: ContextDir is a path to subfolder in the repo. Optional.
                  type: string
                flavor:
                  description: Flavor of the git provider like github, gitlab, bitbucket,
                    generic, etc. Optional.
                  type: string
                httpProxy:
                  description: HttpProxy is optional.
                  type: string
                httpsProxy:
                  description: HttpsProxy is optional.
                  type: string
                noProxy:
                  description: NoProxy can be used to specify domains for which no
                    proxying should be performed. Optional.
                  type: string
                ref:
                  description: Ref is a git reference. Optional. "master" is used
                    by default.
                  type: string
                secretRef:
                  description: SecretRef refers to the secret that contains credentials
                    to access the git repo. Optional.
                  properties:
                    name:
                      description: Name is the name of the secret that contains credentials
                        to access the git repo
                      type: string
                  required:
                  - name
                  type: object
                url:
                  description: URL of the git repo
                  type: string
              required:
              - url
              type: object
            strategy:
              type: string
          required:
          - outputImage
          - source
          - strategy
          type: object
        status:
          description: BuildStatus defines the observed state of Build
          properties:
            status:
              type: string
          required:
          - status
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
