apiVersion: build.dev/v1alpha1
kind: Build
metadata:
  name: example-build
spec:
  # Add fields here
  source:
    url: https://github.com/sclorg/nodejs-ex
  strategy: "buildpacks-v3"
  builderImage: "cloudfoundry/cnb:bionic"
  outputImage: "image-registry.openshift-image-registry.svc:5000/sbose/nodejs-ex"