apiVersion: build.dev/v1alpha1
kind: Build
metadata:
  name: custom-s2i-strategy-example
spec:
  source:
    url: https://github.com/sclorg/nodejs-ex
  strategy: "source-to-image"
  builderImage: "docker.io/centos/nodejs-10-centos7"
  outputImage: "image-registry.openshift-image-registry.svc:5000/sbose/nodejs-ex"