apiVersion: apps/v1
kind: Deployment
metadata:
  name: build-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: build-operator
  template:
    metadata:
      labels:
        name: build-operator
    spec:
      serviceAccountName: build-operator
      containers:
        - name: build-operator
          # Replace this with the built image name
          image: REPLACE_IMAGE
          args:
            - /bin/sh
            - -c
            - touch /tmp/build-operator-healthy
          command:
          - build-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "build-operator"
          livenessProbe:
            exec:
              command:
                - cat
                - /tmp/build-operator-healthy
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - cat
                - /tmp/build-operator-healthy
            initialDelaySeconds: 5
            periodSeconds: 10
