---
apiVersion: shipwright.io/v1alpha1
kind: BuildStrategy
metadata:
  name: buildpacks-v3-heroku
spec:
  buildSteps:
    - name: prepare
      image: heroku/buildpacks:18
      securityContext:
        runAsUser: 0
        capabilities:
          add: 
            - CHOWN
      command:
        - /bin/bash
      args:
        - -c
        - >
          chown -R "1000:1000" /tekton/home &&
          chown -R "1000:1000" /cache &&
          chown -R "1000:1000" /layers
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 65Mi
      volumeMounts:
        - name: cache-dir
          mountPath: /cache
        - name: layers-dir
          mountPath: /layers
    - name: build-and-push
      image: heroku/buildpacks:18
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
      command:
        - /cnb/lifecycle/creator
      args:
        - -app=$(params.shp-source-context)
        - -cache-dir=/cache
        - -layers=/layers
        - $(params.shp-output-image)
      resources:
        limits:
          cpu: 500m
          memory: 1Gi
        requests:
          cpu: 250m
          memory: 65Mi
      volumeMounts:
        - name: cache-dir
          mountPath: /cache
        - name: layers-dir
          mountPath: /layers
