---
apiVersion: build.dev/v1alpha1
kind: BuildStrategy
metadata:
  name: buildpacks-v3
spec:
  buildSteps:
    - name: step-prepare
      image: $(build.builderImage)
      securityContext:
        runAsUser: 0
      command:
        - /bin/bash
      args:
        - -c
        - chown -R "1000:1000" "/workspace/source"
    - name: step-detect
      image: $(build.builderImage)
      securityContext:
        runAsUser: 1000
      command:
        - /cnb/lifecycle/detector
      args:
        - -log-level=debug
        - -app=/workspace/source
        - -group=/layers/group.toml
        - -plan=/layers/plan.toml
      volumeMounts:
        - name: layers-dir
          mountPath: /layers
    - name: step-analyze
      image: $(build.builderImage)
      securityContext:
        runAsUser: 1000
      command:
        - /cnb/lifecycle/analyzer
      args:
        - -log-level=debug
        - -layers=/layers
        - -group=/layers/group.toml
        - $(build.output.image)
      volumeMounts:
        - name: layers-dir
          mountPath: /layers
    - name: step-restore
      image: $(build.builderImage)
      securityContext:
        runAsUser: 1000
      command:
        - /cnb/lifecycle/restorer
      args:
        - -log-level=debug
        - -group=/layers/group.toml
        - -layers=/layers
        - -path=/cache
      volumeMounts:
        - name: cache-dir
          mountPath: /cache
        - name: layers-dir
          mountPath: /layers
    - name: step-build
      image: $(build.builderImage)
      securityContext:
        runAsUser: 1000
      command:
        - /cnb/lifecycle/builder
      args:
        - -app=/workspace/source
        - -layers=/layers
        - -group=/layers/group.toml
        - -plan=/layers/plan.toml
      volumeMounts:
        - name: layers-dir
          mountPath: /layers
    - name: step-export
      image: $(build.builderImage)
      securityContext:
        runAsUser: 0
      command:
        - /cnb/lifecycle/exporter
      args:
        - -app=/workspace/source
        - -layers=/layers
        - -helpers=true
        - -group=/layers/group.toml
        - $(build.output.image)
      volumeMounts:
        - name: layers-dir
          mountPath: /layers
