---
apiVersion: build.dev/v1alpha1
kind: BuildStrategy
metadata:
  name: buildah
spec:
  buildSteps:
    - name: step-buildah-bud
      image: $(build.builderImage)
      workingDir: /workspace/source
      securityContext:
        privileged: true
      command:
        - /usr/bin/buildah
      args:
        - bud
        - --tag=$(build.output.image)
        - --file=$(build.dockerfile)
        - $(build.pathContext)
      volumeMounts:
        - name: buildah-images
          mountPath: /var/lib/containers/storage
    - name: step-buildah-push
      image: $(build.builderImage)
      securityContext:
        privileged: true
      command:
        - /usr/bin/buildah
      args:
        - push
        - --tls-verify=false
        - docker://$(build.output.image)
      volumeMounts:
        - name: buildah-images
          mountPath: /var/lib/containers/storage
