on: 
    pull_request:
      branches: [ master ]
    push:
      branches: [ master ]
name: Unit, Integration, and E2E Tests
jobs:
    unit:
        strategy:
          matrix:
            go-version: [1.15.x]
            os: [ubuntu-latest]
        runs-on: ${{ matrix.os }}
        steps:
        - name: Install Go
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go-version }}
        - name: Check out code
          uses: actions/checkout@v2
        - name: Build
          run: make build
        - name: Test
          run: make test-unit-coverage
    integration:
        strategy:
          fail-fast: false
          matrix:
            go-version: [1.15.x]
            os: [ubuntu-latest]
            kubernetes:
              # Only v1.18 is currently enabled because of the flakiness in the tests, specifically API calls failing with "etcdserver: request timed out"
              #- v1.17.17
              #- v1.18.15
              - v1.19.7
              #- v1.20.2
          max-parallel: 1
        runs-on: ${{ matrix.os }}
        steps:
        - name: Install Go
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go-version }}
        - name: Check out code
          uses: actions/checkout@v2
        - name: Install kubectl
          uses: azure/setup-kubectl@v1
          with:
            version: ${{ matrix.kubernetes }}
        - name: Create kind cluster
          uses: helm/kind-action@v1.1.0
          with:
            version: v0.10.0
            node_image: kindest/node:${{ matrix.kubernetes }}
            cluster_name: kind
            wait: 120s
        - name: Verify kind cluster
          run: |
            echo "# Using KinD context..."
            kubectl config use-context "kind-kind"
            echo "# KinD nodes:"
            kubectl get nodes
        - name: Install Tekton
          run: |
            make kind-tekton
        - name: Test
          run: make test-integration
    e2e:
        strategy:
          fail-fast: false
          matrix:
            go-version: [1.15.x]
            os: [ubuntu-latest]
            kubernetes:
              # Only v1.18 is currently enabled because of the flakiness in the tests, specifically API calls failing with "etcdserver: request timed out"
              #- v1.17.17
              #- v1.18.15
              - v1.19.7
              #- v1.20.2
          max-parallel: 2
        runs-on: ${{ matrix.os }}
        steps:
        - name: Install Go
          uses: actions/setup-go@v2
          with:
            go-version: ${{ matrix.go-version }}
        - name: Check out code
          uses: actions/checkout@v2
        - name: Install kubectl
          uses: azure/setup-kubectl@v1
          with:
            version: ${{ matrix.kubernetes }}
        - name: Create kind cluster
          uses: helm/kind-action@v1.1.0
          with:
            version: v0.10.0
            node_image: kindest/node:${{ matrix.kubernetes }}
            cluster_name: kind
            wait: 120s
        - name: Verify kind cluster
          run: |
            echo "# Using KinD context..."
            kubectl config use-context "kind-kind"
            echo "# KinD nodes:"
            kubectl get nodes
        - name: Install Tekton
          run: |
            make kind-tekton
            kubectl -n tekton-pipelines rollout status deployment tekton-pipelines-controller --timeout=1m
            kubectl -n tekton-pipelines rollout status deployment tekton-pipelines-webhook --timeout=1m
        - name: Install Registry
          run: |
            kubectl apply -f test/data/registry.yaml
            kubectl -n registry rollout status deployment registry --timeout=1m
        - name: Install ko
          run: curl -fsL https://github.com/google/ko/releases/download/v0.8.1/ko_0.8.1_Linux_x86_64.tar.gz | sudo tar xzf - -C /usr/local/bin ko
        - name: Install Shipwright Build
          run: |
            make install-controller-kind
            kubectl -n shipwright-build rollout status deployment shipwright-build-controller --timeout=1m || true
        - name: Test
          env:
            TEST_PRIVATE_REPO: true
            TEST_PRIVATE_GITHUB_SSHAUTHPRIVATEKEY: ${{ secrets.SAMPLE_RUBY_PRIVATE_SSHKEY }}
            TEST_PRIVATE_GITHUB_SECRET: sample-private-github-sshkey
          run: |
            export TEST_NAMESPACE=shipwright-build
            export TEST_IMAGE_REPO=registry.registry.svc.cluster.local:32222/shipwright-io/build-e2e
            if [ "${{ secrets.CI_USER_PRIVATE_SSH_BASE64 }}" != "" ]; then
              export TEST_PRIVATE_REPO=true
              export TEST_SOURCE_SECRET=test-source-secret
              export TEST_PRIVATE_GITHUB=git@github.com:shipwright-io/sample-nodejs-private.git
              cat <<EOF | kubectl apply -n "${TEST_NAMESPACE}" -f -
            ---
            apiVersion: v1
            kind: Secret
            metadata:
              name: ${TEST_SOURCE_SECRET}
              annotations:
                tekton.dev/git-0: github.com
            type: kubernetes.io/ssh-auth
            data:
              ssh-privatekey: ${{ secrets.CI_USER_PRIVATE_SSH_BASE64 }}
            EOF
            fi

            make test-e2e

        - name: Build controller logs
          if: ${{ failure() }}
          run: |
            echo "# Pods:"
            kubectl -n shipwright-build get pod
            PODS=$(kubectl -n shipwright-build get pod -o json)
            POD_NAME=$(echo "${PODS}" | jq -r '.items[] | select(.metadata.name | startswith("shipwright-build-controller-")) | .metadata.name')
            if [ "${POD_NAME}" != "" ]; then
              RESTART_COUNT=$(echo "${PODS}" | jq -r ".items[] | select(.metadata.name == \"${POD_NAME}\") | .status.containerStatuses[0].restartCount")
              if [ "${RESTART_COUNT}" != "0" ]; then
                echo "# Previous logs:"
                kubectl -n shipwright-build logs "${POD_NAME}" --previous || true
              fi
              echo "# Logs:"
              kubectl -n shipwright-build logs "${POD_NAME}"
            else
              echo "# Pod is missing, there are no logs to retrieve, bailing out..."
            fi
