name: Release

on:
  workflow_dispatch:
    inputs:
      release:
        description: 'Desired tag'
        required: true
      tags:
        description: 'Previous tag'
        required: true

jobs:
  release:
    if: ${{ github.repository == 'shipwright-io/build' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build Release Changelog
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PREVIOUS_TAG: ${{ github.event.inputs.tags }}
      run: |
        # might not be necessary but make sure
        chmod +x "${GITHUB_WORKSPACE}/.github/draft_release_notes.sh"
        export GITHUB_TOKEN
        export PREVIOUS_TAG
        "${GITHUB_WORKSPACE}/.github/draft_release_notes.sh"
    - name: Draft release
      id: draft_release
      uses: actions/create-release@v1
      with:
        release_name: "Shipwright Build release ${{ github.event.inputs.release }}"
        tag_name: ${{ github.event.inputs.release }}
        body_path: Changes.md
        draft: true
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Install Go
      uses: actions/setup-go@v2
    - name: Install Ko
      uses: imjasonh/setup-ko@20b7695b536c640edfafdd378d96c760460f29d6

    - name: Ko resolve release.yaml
      env:
        REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
        REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
        IMAGE_HOST: quay.io
        IMAGE: shipwright/shipwright-operator
      run: make release
    - name: Upload Release Asset
      id: upload_release_asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.draft_release.outputs.upload_url }} 
        asset_path: ./release.yaml
        asset_name: release.yaml
        asset_content_type: application/x-yaml
